- name: install and run nginx
  hosts: web
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enable: yes
