- name: play level variables
  hosts: local
  connection: local
  vars:
    course: "devsecops with aws"
    trainer: "shivkumar"
    ansible.builtin.debug:
      msg: " course= {{ course}} trainer= {{ trainer }}"