- name: print local files
  hosts: local
  connection: local
  vars_files:
    - cour.yaml
  tasks:
   - name: print msg
     ansible.builtin.debug:
       msg: "course: {{ course }} duration: " #{{ duration }} trainer: {{ trainer }}"