- name: ansible command module
  hosts: local
  connection: local
  tasks:
  - name: check command 
    # ansible.builtin.command: date
    ansible.builtin.command: free -m
    register: mem

  - name: print date
    ansible.builtin.debug:
      msg: "{{ mem.stdout }}"
    when: mem.rc == 0