- name: read input during runtime
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: enter username
      private: no
  vars_prompt:
    - name: password
      prompt: enter password
      private: yes
  tasks:
    - name: display username
      ansible.builtin.debug:
        msg: "username is: {{ username }} password is {{ password }}"
